name: Node.js App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure VM
        run: |
          # Add commands to deploy the application to Azure VM
          # For example, using SCP to transfer files and SSH to run deployment script
          scp -r .AgnesAdzoa@Assessment:/path/to/destination
          ssh AgnesAdzoa@Assessment 'bash /path/to/deploy.sh'
